config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :friends_attachments
  #resources :post_attachments
  resources :friends 
    
  root to: 'friends#index'
  #get '/search' => 'friends#search', :as => 'search_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
   # mount_uploaders :images, ImageUploader
   # has_many :friends_attachments
     #accepts_nested_attributes_for :friends_attachments
     validates :first_name, :last_name, :age, presence: true
     validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)*[^@.\s]+\z/ }
     validates :phone, length: { in: 10..12}
     #validates :first_name, :uniqueness => {:message => "already taken"}
     


end

app/models/friends_attachment.rb
class FriendsAttachment < ApplicationRecord
    #mount_uploader :avatar, AvatarUploader
       #belongs_to :friends, optional: true
      # validates :avatar, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friends_attachments_controller.rb
class FriendsAttachmentsController < ApplicationController
  before_action :set_friends_attachment, only: %i[ show edit update destroy ]

  # GET /friends_attachments or /friends_attachments.json
  def index
   # @friends_attachments = FriendsAttachment.all
   respond_to do |format|
    format.html
    format.js { render json: FriendsDatatable.new(view_context) }
  end
  end

  # GET /friends_attachments/1 or /friends_attachments/1.json
  def show
  end

  # GET /friends_attachments/new
  def new
    @friends_attachment = FriendsAttachment.new
  end

  # GET /friends_attachments/1/edit
  def edit
  end

  # POST /friends_attachments or /friends_attachments.json
  def create
    @friends_attachment = FriendsAttachment.new(friends_attachment_params)

    respond_to do |format|
      if @friends_attachment.save
        format.html { redirect_to @friends_attachment, notice: "Friends attachment was successfully created." }
        format.json { render :show, status: :created, location: @friends_attachment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friends_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends_attachments/1 or /friends_attachments/1.json
  def update
    respond_to do |format|
      if @friends_attachment.update(friends_attachment_params)
        format.html { redirect_to @friends_attachment, notice: "Friends attachment was successfully updated." }
        format.json { render :show, status: :ok, location: @friends_attachment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friends_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends_attachments/1 or /friends_attachments/1.json
  def destroy
    @friends_attachment.destroy
    respond_to do |format|
      format.html { redirect_to friends_attachments_url, notice: "Friends attachment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friends_attachment
      @friends_attachment = FriendsAttachment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friends_attachment_params
      params.require(:friends_attachment).permit(:friend_id, :avatar)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /friends or /friends.json
  def index
    #@friends = Friend.all
   
    respond_to do |format|
      format.html
      format.js { render json: FriendsDatatable.new(view_context) }
    end
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
    #@friends_attachment = @friend.friends_attachments.build
    #respond_to do |format|
     # format.js
    #end
  end

  # GET /friends/1/edit
  def edit
    @friends = Friend.find(params[:id])
    respond_to do |format|
      format.html { render :file => "friends/edit.html.erb" }
    end
    #@friends_attachment = @friends.friends_attachments.find_by_id(:id)
    
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        #params[:friends_attachments]['avatar'].each do |a|
         # @friends_attachment = @friend.friends_attachments.create!(:avatar => a,     :friend_id => @friend.id)
       #end
      #format.js { render :file => "friends/create.js.erb", locals: {:message => "New Friend Created Successfully"}} 
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #def search
    #if params[:search].blank?  
     # redirect_to(root_path) and return  
    #else  
     # friends = Friend.find(params[:search])  
      #respond_to do |format|
       # format.html
        #format.js
      #end

    #end 

  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :age, :gender)
      #, post_attachments_attributes: 
      #[:id, :post_id, :avatar])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_attachments_helper.rb
module FriendsAttachmentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/friends/_create_friend_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal123" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

app/views/friends/_form.html.erb
<%= form_for(@friend, :html => { :multipart => true }, :remote => true)  do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      
    <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :first_name, class: "form-label" %>
    <%= f.text_field :first_name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :last_name, class: "form-label" %>
    <%= f.text_field :last_name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.text_field :email, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :phone, class: "form-label",  :maxlength => 12 %>
    <%= f.text_field :phone, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :twitter, class: "form-label" %>
    <%= f.text_field :twitter, class: "form-control", required: true %>
  </div>
  <div class="mb-3">
    <%= f.label :age, class: "form-label" %>
    <%= f.number_field :age, max: 100, min: 1, class: "form-control", required: true %>
    
    
  </div>
  <div class="mb-3">
    <%= f.label :gender, class: "form-label" %>
    
    <%= f.select :gender, ["M","F","Others"], class: "form-control"%>
  </div>
  #<%= f.fields_for :friends_attachments do |p| %>
   <!-- <div class="mb-3">
      #<%= p.label :avatar %><br>
     # <%= p.file_field :avatar, :multiple => true, name:     "friends_attachments[avatar][]",  class: "form-control", required: true %>
    </div> -->
  #<% end %>
 

  <div class="mb-3">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/friends/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Friends</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        
        
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign Out",
          destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add friend",
          new_friend_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile",
          edit_user_registration_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign Up",
        new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In",
        new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
       
        
       
      </ul>
     
    </div>
  </div>
</nav>

app/views/friends/create.js.erb
$("#modal-window").modal('toggle');
var t = $('#friendstable').DataTable();
  t.ajax.reload();

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Add Friend', new_friend_path, {:remote => true,  class: 'btn btn-success'} %>


<div class = 'create-modal-body'>
</div>
</br>
</br>
<div id="container">
<div id="label">Filters</div>
<div id="element1">
<legend class="custom_legend_age">AGE</legend>



<%= text_field_tag "minimum_age", '', class: 'minimum-age', placeholder: 'From' %>


<%= text_field_tag "maximum_age", '', class: 'maximum-age', placeholder: 'To' %>

</div>


<div class="vl"></div>
    <div class = container2>
              <legend class="custom_legend">Gender</legend>
              <div class="row">
                <div class="col-md-12">
                  <span class="chkbx_search">
                    <input type="radio" name="gender" id="gender_type_m" value="M">
                    <label for="gender_type_m">Male</label>
                  </span>
                  <span class="chkbx_search">
                    <input type="radio" name="gender" id="gender_type_f" value="F">
                    <label for="gender_type_f">Female</i></label>
                    </span>
                </div>
              </div>
    </div>


</div>


<br>
<br>


<br>
<br>
<table id="friendstable" class = "table table-striped table-bordered" style = "width:100%" >
<thead>
<tr>
  <th>First name</th>
  <th>Last name</th>
  <th>Email</th>
  <th>Phone</th>
  <th>Age</th>
  <th>Twitter</th>
  <th>Gender</th>
  <th>Action</th>

  
</tr>
<tr>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>

<tbody>
</tbody>
</table>

<br>

<script>


$(document).ready(function(){
  
var table = $("#friendstable").DataTable({
"processing": true,
        "serverSide": true,
        "columnDefs": [{ "orderable": false, "targets": -1 }],
        "ajax":{
          "url": $('#friendstable').data('source'),
          "data": function (d) {
            
             d.minimum_age = $("input[name='minimum_age']").val(),
            
            d.maximum_age = $("input[name='maximum_age']").val(),
            d.gender = $("input[name='gender']:checked").val()
          },
          
        },

        "pagingType": "full_numbers",
        "columns": [
            {"data": "first_name"},
            {"data": "last_name"},
            {"data": "email"},
            {"data": "phone"},
            {"data": "age"},
            {"data": "twitter"},
            {"data": "gender"},
            {data: 'action', 'sortable': false}
            
        ],
        
        
            
});




$('#friendstable thead tr:eq(1) th').each(function() {
  $(this).html('<input type="text" style="width:100%;align=center;" class="form-control" />');
});



table.columns().every(function(index) {
  var that = this;

  $('#friendstable thead tr:eq(1) th:eq(' + index + ') input').on('keyup change', function() {
    if (that.search() !== this.value) {
      that
        .search(this.value)
        .draw();
    }
  });
  
});
$(document).on('keyup change', "input[name='minimum_age'], input[name='maximum_age']",function (){

      if($("input[name='minimum_age']").val().length || $("input[name='maximum_age']").val().length) {
        table.draw();
      }
    });
    $(document).on('change', "input[name='gender']",function (){
      table.draw();
    });
    

});



</script>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path ,  class: 'btn btn-success'%>

app/views/friends/new.js.erb
jQuery('.create-modal-body').html("<%= escape_javascript render(:partial => 'create_friend_modal', :locals => { :obj => @friend }) %>");
jQuery.noConflict();
jQuery('#myModal123').modal('show');

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @friend.twitter %>
</p>
<p>
  <strong>Age:</strong>
  <%= @friend.age %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/friends_attachments/_form.html.erb
<%= form_for(friends_attachment) do |f| %>
  <% if friends_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friends_attachment.errors.count, "error") %> prohibited this friends_attachment from being saved:</h2>

      <ul>
      <% friends_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :friend_id %>
    <%= f.number_field :friend_id %>
  </div>

  <div class="field">
    <%= f.label :avatar %>
    <%= f.text_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends_attachments/edit.html.erb
<h1>Editing Friends Attachment</h1>

<%= render 'form', friends_attachment: @friends_attachment %>

<%= link_to 'Show', @friends_attachment %> |
<%= link_to 'Back', friends_attachments_path %>

app/views/friends_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friends Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Friend</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends_attachments.each do |friends_attachment| %>
      <tr>
        <td><%= friends_attachment.friend_id %></td>
        <td><%= friends_attachment.avatar %></td>
        <td><%= link_to 'Show', friends_attachment %></td>
        <td><%= link_to 'Edit', edit_friends_attachment_path(friends_attachment) %></td>
        <td><%= link_to 'Destroy', friends_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friends Attachment', new_friends_attachment_path %>

app/views/friends_attachments/new.html.erb
<h1>New Friends Attachment</h1>

<%= render 'form', friends_attachment: @friends_attachment %>

<%= link_to 'Back', friends_attachments_path %>

app/views/friends_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Friend:</strong>
  <%= @friends_attachment.friend_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @friends_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_friends_attachment_path(@friends_attachment) %> |
<%= link_to 'Back', friends_attachments_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css'/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js'></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
    <link href = "https://code.jquery.com/jquery-3.5.1.js"></link>
    <link href = "https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></link>
  </head>
  <body>
  <%= render 'friends/header' %>
<div class = "container-xxl">
  <%= yield %>
  </div>
    

    

    
  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/pages/home.html.erb
<div class="container table-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <table id="static-table" class="display">
        <thead>
        <tr>
          <th>Column1</th>
          <th>Column2</th>
          <th>Column3</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Data11</td>
          <td>Data12</td>
          <td>Data13</td>
        </tr>
        <tr>
          <td>Data21</td>
          <td>Data22</td>
          <td>Data23</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>